language: csharp
dist: xenial
sudo: false

dotnet: 2.2.103

mono:
  - 5.18.0
  - latest

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - libzmq3-dev

services:
- docker

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - TMPDIR=/tmp

script:
- travis_wait make

after_success:
- make ci_push

notifications:
  email: false
