language: csharp
dist: xenial
sudo: false
dotnet: 2.2.103

matrix:
  fast_finish: true

  include:
    - os: linux
      mono: 5.10.0
    - os: linux
      mono: 5.18.0
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.2
      mono: 5.18.0
    - os: osx
      osx_image: xcode9.3beta
      mono: latest

  allow_failures:
    - os: linux
    - mono: weekly
    - mono: latest

addons:
  apt:
    packages:
    - libzmq3-dev

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - TMPDIR=/tmp

script:
  - travis_wait ./fake.sh build

notifications:
  email: false
