language: csharp
mono: none
dist: xenial
sudo: false
dotnet: 2.2

addons:
  apt:
    packages:
    - libzmq3-dev

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - TMPDIR=/tmp

script:
  - travis_wait ./fake.sh build

notifications:
  email: false
