# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: docs
build:
  local:
    useDockerCLI: false
  artifacts:
  - image: logary/docs-web
    context: docs

deploy:
  kubeContext: docker-desktop
  kustomize:
    paths:
    - docs/k8s/dev
    - examples/shared/k8s/dev

portForward:
- resourceType: Service