apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../as-deployment
- horizontalpodautoscaler.yaml
- poddisruptionbudget.yaml

patchesStrategicMerge:
- deployment.yaml

commonLabels:
  app: logary
  component: rutta

namespace: logary