apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- headless-service.yaml
- daemonset.yaml

commonLabels:
  app: logary
  component: rutta

namespace: logary