# gcloud builds submit --project $PROJECT_ID . --config cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/bash'
  args:
  - -c
  - echo "${FONTAWESOME_AUTH_TOKEN}" >.npmrc
  env:
  - FONTAWESOME_AUTH_TOKEN=${_FONTAWESOME_AUTH_TOKEN}

- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -f
  - docs/Dockerfile
  - -t
  - eu.gcr.io/$PROJECT_ID/logary-site:$COMMIT_SHA
  - -t
  - eu.gcr.io/$PROJECT_ID/logary-site:latest
  - docs

- name: gcr.io/cloud-builders/docker
  args: ["push", "eu.gcr.io/$PROJECT_ID/logary-site:$COMMIT_SHA" ]

- name: gcr.io/cloud-builders/docker
  args: ["push", "eu.gcr.io/$PROJECT_ID/logary-site:latest" ]

- name: gcr.io/cloud-builders/kubectl
  args: ["--namespace=logary", "set", "image", "deployment/logary-site", "logary-site=eu.gcr.io/$PROJECT_ID/logary-site:$COMMIT_SHA"]
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}

substitutions:
  _CLOUDSDK_COMPUTE_ZONE: 'CHANGE_ME'
  _CLOUDSDK_CONTAINER_CLUSTER: 'CHANGE_ME'
  _FONTAWESOME_AUTH_TOKEN: 'CHANGE_ME'

tags:
- oss
