# This service will round-robin requests to Rutta
apiVersion: v1
kind: Service
metadata:
  name: rutta

spec:
  ports:
  - name: http-json
    port: 80
    targetPort: http-json

  - name: udp-json
    port: 14001
    targetPort: udp-json
    protocol: UDP

  # Available from k8s 1.17 (GKE is at 1.15/1.16 and docker-desktop is at 1.16 at the time of writing)
  #topologyKeys:
  #- "kubernetes.io/hostname"
  #- "topology.kubernetes.io/zone"
  #- "topology.kubernetes.io/region"
  #- "*"